### ISSUE TITLE
NETOBSERV-387 Filter out namespaces 

### ISSUE THREAD

**Issue by eranra** [netobserv/network-observability-console-plugin#328]
Question: in the UI filter, can I filter out some namespace?
I want to remove all the pods from kube-admin. For example

@jpinsonneau 
@kfirtoledo

**Comment by kfirtoledo** [comment]
I think it is a good solution.

**Comment by jpinsonneau** [comment]
@andrew-ronaldson FYI, maybe you have good comparaisons to bring :cat: 

@eranra @kfirtoledo do you guys plan to implement this by yourself ? I can guide you if needed
On our side we have [identified it](https://issues.redhat.com/browse/NETOBSERV-387)  but it's not part of our priorities.

**Comment by eranra** [comment]
Hi @andrew-ronaldson Unfortunately, no one knows UI enough to implement. We will have to wait for you or @jpinsonneau to help with that. But, what we are doing is reorganizing the namespaces in our demo to fit. Priorities, yes :-)
